### ISSUE TITLE
Phone Number Input Validation Feature Flaw

### ISSUE THREAD

**Issue by marclzh** [marclzh/pe#7]
Since the application is targeted to NUS students, the phone number field being allowed to be any length above 3 might be a feature flaw. Although UG states that it allows 3 digits for emergency numbers, being a task management app for NUS students, this may not be applicable. Also, allowing 4,5,6 digits may not be applicable due to the reason stated below.

![image.png](https://raw.githubusercontent.com/marclzh/pe/main/files/f03c7b02-6444-4647-a6f7-6c702390154d.png)

Since the international standard for phone numbers is between 7 and 15 numbers, allowing phone numbers greater than 15 and less than 7 would not be necessary.

**Comment by nus-se-script** [comment]
# Team's Response
We have added relevant validation and restrictions to reject user inputs that are not phone numbers, i.e. non-integer and lesser than 3 numbers. 


![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/54d4567f-24af-49d3-a37e-28468cfb252a.png)

![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/425df2b2-1dcd-4925-98a6-e290ee255cda.png)


Further validation of phone number is up to the user's discretion, it is not in the scope of the project to justify what exactly constitutes a phone number and what does not.
# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.NotInScope`]

- [x] I disagree

**Reason for disagreement:** Since this is an application targeted towards NUS students, it is unlikely for the phone number to be lesser than 7 numbers, as seen in the original bug report. Allowing numbers less than 7 could cause users to misinput the phone number of the contact they are trying to save, and lead to difficulty in contacting the intended person otherwise. Hence I still believe that this constitutes a feature flaw, although having a low severity, and affecting only a small number of users.

-------------------
